server {
    listen 80;
    listen [::]:80;
    server_name 20.5.18.246;
    root /var/www/ej-eco/public;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /html/;
    }

    # 禁止访问 .git 目录
    location ~ /\.git {
        deny all;
        access_log off;
        log_not_found off;
    }

    # 处理 PHP 请求
    location ~ \.php$ {
        include fastcgi_params;
        # fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_intercept_errors on;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 3600;
        fastcgi_read_timeout 3600;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }

    # 禁止访问隐藏文件
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # 处理静态文件缓存
    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log off;
        log_not_found off;
        expires max;
    }
}
